create table if not exists appointments (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null,
  doctor text not null,
  appointment_date date not null,
  appointment_time time not null,
  reason text,
  created_at timestamptz default now()
);